-- Run this in your Supabase SQL Editor to add the new tracking columns
ALTER TABLE mobility_scans 
ADD COLUMN IF NOT EXISTS min_rom FLOAT8,
ADD COLUMN IF NOT EXISTS velocity FLOAT8,
ADD COLUMN IF NOT EXISTS jitter FLOAT8,
ADD COLUMN IF NOT EXISTS acceleration FLOAT8;

-- Optional: If you want to see the full table definition for reference:
/*
CREATE TABLE mobility_scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  supabase_user_id UUID REFERENCES auth.users(id),
  muscle TEXT,
  joint_key TEXT,
  max_rom FLOAT8,
  min_rom FLOAT8,
  average_rom FLOAT8,
  previous_rom FLOAT8,
  peak_delta FLOAT8,
  velocity FLOAT8,
  jitter FLOAT8,
  acceleration FLOAT8,
  ml_classification INT,
  ml_status TEXT,
  ai_message TEXT
);
*/
